### ISSUE TITLE
Low number of taxonomy assignments generated by Kraken 

### ISSUE THREAD

**Issue by HitMonk** [bxlab/metaWRAP#258]
Hello,
Im using Metawrap on rhizosphere samples with ~8 million reads each. However, when i sum up the read abundances present in the first column of the .krona files (same files used to generate kronagrams if im not mistaken) i only get ~2 million taxanomy assignments. A 25% taxanomy assignment seems really low, am I doing something wrong or are these conventional numbers that other people also see? Im just surprised that more assignments arent present even at say higher taxonomy levels (Phylum, Family etc)

Also, if i wanted to plot basic taxa bar plots, would you suggest me to use these .krona files? Is there any way that I can improve the number of assignments? In one of the other threads you mentioned that we could try to assign taxonomy at the contig level. Does this mean that Ill have to assemble each sample separately and then use the assembled contigs per sample to assign taxonomy?

Command used to generate kronagrams:
`metawrap kraken -t 53 -o Step3_kraken_comp_taxa Clean_reads/G*.fastq Step2a_megahit/final.contigs.fa`

Abundance in .krona files:
`awk '{sum+=$1} END {print sum}' Gen1-100-S6.krona`
2123293

Total number of reads:
`grep -c "@NB5" Gen1-100-S6_1.fastq`
8138203

**Comment by ursky** [comment]
Good question. 25% assigned is actually quite good in most metagenomic samples! I routinely get <10% in my work with extremophiles. The issue is that for novel organisms that are not in the database, you need a certain amount of information (homology) to estimate the closest relative that is in the database. Illumina reads just don't have enough sequence information for this, unless the read lies in a well-conserved region (probably a gene).  

To combat this you could assign taxonomy to the assembly, map the reads to the assembly, and then you know the taxonomy of many more reads because of the contig they mapped to. I use this approach in my work, but its a bit more advanced than intended in metaWRAP.

**Comment by ursky** [comment]
And yes, the .krona files are perfect for making your own plots.

**Comment by HitMonk** [comment]
Ah, okay that makes sense. Just to confirm, when you say assign taxonomy to contigs, you mean do it separately from the Metawrap pipeline? Say, using Blast or Diamond? Is there a particular tool that you prefer?

**Comment by ursky** [comment]
Nope, I use kraken on the assembly for taxonomy assignment.

**Comment by HitMonk** [comment]
perfect, Thank you for your response, and for the work you put into the package.
