### ISSUE TITLE
Error at Functional annotation step (annotate_bins)

### ISSUE THREAD

**Issue by srikanthkris** [bxlab/metaWRAP#306]
hi ,

I am getting an error at the functional annotation step.

The command is 

metawrap annotate_bins -o ./FUNCT_ANNOT -t 80 -b BIN_REASSMBLY/reassembled_bins

The error i am getting is
could not run command: tbl2asn -V b -a r10 ...

i have attached a photo with the error message. I am getting outputs of prokka. 

Thanks

![error](https://user-images.githubusercontent.com/7313434/94660778-1b420080-0341-11eb-9e27-86b436817ffa.png)

**Comment by ursky** [comment]
I think this is a warning, not an error. Does the program finish? This happens because tbl2asn annoyingly enforces the NCBI database to be super up-to-date (it doesn't actually matter for the annotation, only if you are uploading to NCBI right after). This causes the process to exit with a non-0 exit code. If the annotation finishes, ignore these messages.

**Comment by srikanthkris** [comment]
Thanks
