### ISSUE TITLE
The default bin_refinement module failed to keep the redundant sequences only in the best bin

### ISSUE THREAD

**Issue by DOieGYuan** [bxlab/metaWRAP#320]
Dear ursky,
        Thanks for providing this awesome tool for genomic-centric metagenomics.
        I was puzzled when using "bin_refinement" module to refine CONCOCT, Metabat2, and MaxBin2 results. As indicated in the help page, for contigs that end up in more than one bin, the default action is to keep them only in the best bin. However, I found the redundant sequences **still remained** in many genomes. And I also found strings like ```flag_1 multi_5.0000 len_2485``` were added to the names of redundant sequences. 
       Thanks for the help!

**Comment by ursky** [comment]
I would revisit the input folders you gave bin_rifinement. From your comment about the program adding `flag_1 multi_5.0000 len_2485` i am 100% certain this is an input issue - the bin refiner does not modify contig names - this type of info is added by the assembler. The only way contigs can be duplicated in the final results is if:

1. Two bin sets have slightly different naming conventions because of some automatic renaming - for example something like `contig_1_len=10` vs `contig1_len_10`, or `contig_1` vs `contig_1 flag_1 multi_5.0000 len_2485`.
2. The input bin sets did not originate from the same assembly. Carefully double-check this - the contigs in sets A, B, and C need to be identical in sequence and name down the characters.

**Comment by DOieGYuan** [comment]
Thanks for your rapid reply.
Indeed, this was an issue caused by the header name provided by the assembler. No space should be used because CONCOCT won't change the header name but Maxbin and metabat will. This produced redundant sequences with different names.

**Comment by var-chenm4680** [comment]
Hello, I hope your research is going well.
I have a question about refine_bins. I have binning results from CONCOCT, MetaBAT2, and MaxBin2. I noticed there are also "unbinned" files and other non-bin files in the output. Should these be removed or moved elsewhere before running bin_refinement? I encountered a file-related error when running the module.
