### ISSUE TITLE
Questions about future of metaWRAP

### ISSUE THREAD

**Issue by jolespin** [bxlab/metaWRAP#324]
Hi @ursky , 
Your tool, to my knowledge, is the best software suite for metagenomics.  In particular, I use it for merging genome bins.  I was wondering if you had any plans for the following: 
1) Update to use Python 3 instead of Python 2.  CheckM was recently rewritten in Python 3 which I believe was one of the main limitations before.  I could help with this once my PhD program mellows out a bit. 
2) Incorporate methods to bin and evaluate protists.  There was a tool that came out like CheckM but for protists that could be useful for this: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02155-4 The only problem is that a lot of binners avoid addressing protist binning
3) An option to use DAS_tool for the bin refinement as an alternative
4) An option for long read binners

I also recently discovered some other binners that could be useful: 
[GraphBin](https://academic.oup.com/bioinformatics/article-abstract/36/11/3307/5804980?redirectedFrom=fulltext) bins directly from de Bruijn graphs which seems pretty cool

[MetaBMF ](https://academic.oup.com/bioinformatics/article/36/2/356/5538989?itm_content=bioinformatics&itm_source=trendmd-widget&itm_campaign=trendmd-pilot&itm_medium=sidebar)

[SolidBin](https://academic.oup.com/bioinformatics/article/35/21/4229/5448864?itm_content=bioinformatics&itm_source=trendmd-widget&itm_campaign=trendmd-pilot&itm_medium=sidebar)

I know all of this is a lot of work. I was just wondering what your plans were and if any of these were areas of interest. 

Thanks, 
-Josh

**Comment by ursky** [comment]
Hi Josh, thank you for the kind words. I completely agree, and I am very aware of the current limitations and pitfalls of metaWRAP. Not only is it a couple of years out-of-date (which happens almost immediately in bioinformatics), but I wrote it when I had just learned bash/python programming, so the infrastructure is amateur at best. Because of both limited time (I have an unrelated full-time job) and outdated design, I do not intend to revamp metaWRAP in any major way in the near future. The software still works well for what it is and many enjoy using it. I will continue making minor changes and fixes as I have been for the last two years. 

That said, it would actually be easier to remake it from scratch with proper pythonic architecture, and I am open to the idea of eventually making MetaWrap2. There are a few considerations: 1) I would like to wait at least 4-5 years after the release of MetaWrap to allow for some newer innovations, 2) I would need to find a time in my life when I have the personal time to do it, and 3) I will need a lab and PI to collaborate with to sponsor the development and publication. One day these will align, but for now, I think metaWRAP is still a good (and of course - flawed) tool for what I made it for.

**Comment by jolespin** [comment]
I agree  100%, I just wanted to see what your thoughts were regarding this.  Yes, I can imagine that must be difficult to constantly develop a package when your career has changed.  metaWRAP is still my favorite tool to use and a lot of researchers at my institute use the environment I made for it.  I think that's a great idea to wait a few years before doing a revamp of the package because the field is rapidly growing.  I wasn't aware of consensus binning until I used your program and it seems like the best way moving forward to use the results from multiple binning programs.  Looking forward to the day when binners will handle both protists and prokaryotes as I have some datasets sitting around that have a mix.
